# Generated by Django 2.2.10 on 2021-05-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(max_length=50)),
                ('advisor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.Advisor')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userAPI.User')),
            ],
        ),
    ]
